// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Fetch from "bs-fetch/src/Fetch.bs.js";
import * as React from "react";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

function ws(webSocket) {
  return {
          id: Json_decode.field("id", Json_decode.string, webSocket)
        };
}

var Decode = {
  ws: ws
};

function App(Props) {
  var match = React.useReducer((function (param, action) {
          if (typeof action === "number") {
            if (action !== 0) {
              return /* ERROR */1;
            } else {
              return /* LOADING */0;
            }
          } else {
            return /* LOADED */{
                    _0: action._0
                  };
          }
        }), /* LOADING */0);
  var dispatch = match[1];
  var state = match[0];
  Curry._1(dispatch, /* FETCHCHANNEL */0);
  fetch("/", Fetch.RequestInit.make(/* Post */2, {
                    "Content-Type": "application/json"
                  }, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined)).then(function (prim) {
            return prim.json();
          }).then(function (json) {
          var webSocket = ws(json);
          return Promise.resolve(Curry._1(dispatch, /* WEBSOCKET */{
                          _0: webSocket.id
                        }));
        }).catch(function (_err) {
        return Promise.resolve(Curry._1(dispatch, /* FAILEDTOFETCH */1));
      });
  React.useEffect((function () {
          
        }), []);
  if (typeof state === "number") {
    if (state !== 0) {
      return React.createElement("div", undefined, "An Error Occured !!");
    } else {
      return React.createElement("div", undefined, React.createElement("div", undefined, "Loading... "));
    }
  } else {
    return React.createElement("div", undefined, React.createElement("div", undefined, "Loaded" + state._0));
  }
}

var make = App;

export {
  Decode ,
  make ,
  
}
/* react Not a pure module */
