// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Phx_socket from "./phx_socket.bs.js";
import * as Phx_channel from "./phx_channel.bs.js";
import * as Phx_presence from "./phx_presence.bs.js";

function putOn($$event, f, channel) {
  channel.on($$event, f);
  return channel;
}

function removeChannel(channel, socket) {
  return socket.remove(channel);
}

function putOnClose(f, socket) {
  socket.onClose(f);
  return socket;
}

function putReceive($$event, handleReiceive, push) {
  push.receive($$event, handleReiceive);
  return push;
}

var Abstract;

var Channel;

var Socket;

var Push;

var Presence;

var LongPoll;

var initSocket = Phx_socket.init;

var initChannel = Phx_socket.channel;

var joinChannel = Phx_channel.join;

var leaveChannel = Phx_channel.leave;

var push = Phx_channel.push;

var disconnectSocket = Phx_socket.disconnect;

var connectSocket = Phx_socket.connect;

var putOnSyncState = Phx_presence.onState;

var putOnsyncDiff = Phx_presence.onDiff;

export {
  Abstract ,
  Channel ,
  Socket ,
  Push ,
  Presence ,
  LongPoll ,
  initSocket ,
  initChannel ,
  joinChannel ,
  leaveChannel ,
  push ,
  putOn ,
  disconnectSocket ,
  connectSocket ,
  removeChannel ,
  putOnClose ,
  putReceive ,
  putOnSyncState ,
  putOnsyncDiff ,
  
}
/* Phx_socket Not a pure module */
