// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Phoenix from "phoenix";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function init(opts, path) {
  return new Phoenix.Socket(path, opts !== undefined ? Caml_option.valFromOption(opts) : undefined);
}

function initChannel(params, socket, topic) {
  return new Phoenix.Channel(topic, params !== undefined ? Caml_option.valFromOption(params) : undefined, socket !== undefined ? Caml_option.valFromOption(socket) : undefined);
}

function channel(topic, chanParams, socket) {
  return socket.channel(topic, chanParams !== undefined ? Caml_option.valFromOption(chanParams) : undefined);
}

function disconnect(callback, code, reason, socket) {
  socket.disconnect(callback !== undefined ? Caml_option.valFromOption(callback) : undefined, code !== undefined ? Caml_option.valFromOption(code) : undefined, reason !== undefined ? Caml_option.valFromOption(reason) : undefined);
  return socket;
}

function connect(params, socket) {
  socket.connect(params !== undefined ? Caml_option.valFromOption(params) : undefined);
  return socket;
}

export {
  init ,
  initChannel ,
  channel ,
  disconnect ,
  connect ,
  
}
/* phoenix Not a pure module */
