// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Phx_socket$BucklescriptPhx from "./phx_socket.bs.js";
import * as Phx_channel$BucklescriptPhx from "./phx_channel.bs.js";
import * as Phx_presence$BucklescriptPhx from "./phx_presence.bs.js";

function putOn($$event, f, channel) {
  channel.on($$event, f);
  return channel;
}

function removeChannel(channel, socket) {
  return socket.remove(channel);
}

function putOnClose(f, socket) {
  socket.onClose(f);
  return socket;
}

function putReceive($$event, handleReiceive, push) {
  push.receive($$event, handleReiceive);
  return push;
}

var Channel;

var Socket;

var Presence;

var LongPoll;

var initSocket = Phx_socket$BucklescriptPhx.init;

var initChannel = Phx_socket$BucklescriptPhx.channel;

var joinChannel = Phx_channel$BucklescriptPhx.join;

var leaveChannel = Phx_channel$BucklescriptPhx.leave;

var push = Phx_channel$BucklescriptPhx.push;

var disconnectSocket = Phx_socket$BucklescriptPhx.disconnect;

var connectSocket = Phx_socket$BucklescriptPhx.connect;

var putOnSyncState = Phx_presence$BucklescriptPhx.onState;

var putOnsyncDiff = Phx_presence$BucklescriptPhx.onDiff;

export {
  Channel ,
  Socket ,
  Presence ,
  LongPoll ,
  initSocket ,
  initChannel ,
  joinChannel ,
  leaveChannel ,
  push ,
  putOn ,
  disconnectSocket ,
  connectSocket ,
  removeChannel ,
  putOnClose ,
  putReceive ,
  putOnSyncState ,
  putOnsyncDiff ,
  
}
/* Phx_socket-BucklescriptPhx Not a pure module */
