// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Phoenix from "phoenix";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function join(timeout, channel) {
  return channel.join(timeout !== undefined ? Caml_option.valFromOption(timeout) : undefined);
}

function leave(timeout, channel) {
  return channel.leave(timeout !== undefined ? Caml_option.valFromOption(timeout) : undefined);
}

function initPush($$event, payload, timeout, channel) {
  return new Phoenix.Push(channel, $$event, payload, timeout);
}

function push($$event, payload, timeout, channel) {
  return channel.push($$event, payload, timeout !== undefined ? Caml_option.valFromOption(timeout) : undefined);
}

export {
  join ,
  leave ,
  initPush ,
  push ,
  
}
/* phoenix Not a pure module */
